---
# FILE:            {{ role_path }}/ad-hoc-alb/show-alb-hosts-facts.yml
# LICENSE:         Public Domain

#    ansible-playbook roles/ap-application-load-balancer/ad-hoc-alb/show-netstat-used-ports.yml -i hosts.yml
#    ansible-playbook show-netstat-used-ports.yml -i hosts.yml
#    ansible all -a "netstat -ntulp" -i hosts.yml

- name: "ansible-ad-hoc | show-ports-open.yml"
  hosts: all
  gather_facts: no
  tasks:
    - name: "ansible-ad-hoc | show-ports-open.yml | sudo netstat -ntulp"
      shell: "netstat -ntulp"
      become: "yes"
      changed_when: false
      register: ad_hoc_alb_netstat_ntulp_verbose

    - debug: 
        msg: "{{ ad_hoc_alb_netstat_ntulp_verbose.stdout_lines }}"
